#!/usr/bin/env bash
# This script displays the content of the file '/etc/passwd.'
# The script only displays:
# username.
# user id.
# Home directory path for the user.
# Uses the 'while' loop.

while read -r passwd; do
  echo "$passwd" | cut -d ':' -f1,3,6
done < "/etc/passwd"
