#!/usr/bin/env bash
# This script displays the visitor IP along with the HTTP status code from the Apache log file.
# Formats: IP HTTP_CODE in a list format.
# Uses 'awk' command.

awk '{print $1 " " $9}' apache-access.log
