#!/usr/bin/env bash
# This script groups visitors by their IP and HTTP status code, and displays the following data in this exact format:
# OCCURENCE_NUMBER IP HTTP_CODE.
# In list format.
# Ordered from the greatest to the lowest number of occurrences.
# And uses the 'awk' command.

awk '{ print $1 " " $9}' apache-access.log | sort | uniq -c | sort -rn
