#!/usr/bin/env bash
# This script demonstrates a loop from 1 to 10 using the 'while' loop, but 
# for the 4th loop iteration, displays 'bad luck'
# for the 8th loop iteration, displays 'good luck'
# for the other iterations, displays 'Best School' using the 'if', 'elif' and 'else' statements.

counter=1

while [ $counter -le 10 ]; do
    if [ $counter -eq 4 ]; then
        echo "bad luck"
    elif [ $counter -eq 8 ]; then
        echo "good luck"
    else
        echo "Best School"
    fi
    ((counter++))
done
