#!/usr/bin/env bash
# This script displays the content of the current directory.
# In a list format.
# Where only the part of the name after the first dash is displayed.
# And uses the 'for' loop. 
# Does not display hidden files.

list=$(ls)
for i in $list; do
  echo "$i" | cut -d '-' -f2
done
